version: '3.4'

services:
  servicebusmessagesender:
    image: servicebusmessagesender:dev
    container_name: ServiceBusMessageSender
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ServiceBusMessageSender"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_servicebusmessagesender$
    volumes:
      - C:\SUNIL\Practise\ServiceBusMessageReceiver\ServiceBusMessageReceiver\ServiceBusMessageSender:/app
      - C:\SUNIL\Practise\ServiceBusMessageReceiver\ServiceBusMessageReceiver:/src
      - C:\Users\sunil\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_servicebusmessagesender$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_servicebusmessagesender$ \"/app/bin/Debug/net5.0/ServiceBusMessageSender.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true